### ISSUE TITLE
(Read this before report) Bug and crash list

### ISSUE THREAD

**Issue by BlackHole338** [ArkTechMC/IceAndFire-Fabric#21]
Crashes:
-Shift click equipping dragon armor in the dragon stats interface crashes the game 
-Equipping troll armor crashes the game
-Placing a dreadstone torch crashes the game

Bugs:
-Cyclops turns invisible for a few seconds occasionally 
-Ice and fire armor is not correctly shown on the player when equipped except for myrmex armor,(works) sheep disguise armor,(works) and dragon scale armor.(Has no texture)
-Most particle effects do not have a texture including hydra spit, siren heart particles, dread torches, dread lich magic, and pixie dust.
 -Dragons can't be stored in the dragon horn, it just deletes them and makes the horn unusable
-Equipment that applies effects will apply it without being equipped. The blindfold applies blindness while being in the inventory instead of while being equipped and the tide guardian armor applies water breathing while just being in the inventory.
-When you use the cockatrice scepter on an enemy the wither beam keeps going in the direction you shot it until you right click even when the enemy is dead. This is visible if you go in 3rd person or look at yourself in your inventory.
-All arrows except dragon bone arrows cannot be used
-Chain lines function correctly but visibly they never disappear until the mob is killed and the chain goes in a random direction instead of towards the block.
 -Death worm gauntlet when used does not latch out towards enemies but instead extends in the inventory and model visually.
-Regular fire dragon breath does not create fire effects.
-Siren flute effect does not work
-Lightning dragons will keep blasting lightning in the same spot instead of redirecting it to where their enemy moved
-Amethyst lighting dragon scales and amethyst lightning dragons do not have textures but still function
-Sirens can't lure you in
-Troll weapons are invisible
-Myrmex queen disappears permanently through the wall or suffocates in the wall. This happens every time a myrmex queen is generated.

![Screenshot 2024-07-02 202859](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/a771eae0-bb40-4b79-94f5-a23991919b52)

![Screenshot 2024-07-02 202941](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/ae6ecd83-8f72-47ff-8368-6f4728548d0a)

![Screenshot 2024-07-02 203120](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/cb4da924-93b3-4562-8018-3248d3bf6be0)

![Screenshot 2024-07-02 203657](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/17f37136-772a-4c57-adfc-2cfeb7b1c657)

![Screenshot 2024-07-02 203938](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/361a0efc-3cd0-417d-bfd2-2bff2791f47c)

![Screenshot 2024-07-02 204333](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/e2da1445-e692-4991-b922-9b2b286b54cd)

![Screenshot 2024-07-02 204406](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/420a281d-aed7-46b7-958f-627e5dcf62da)

![Screenshot 2024-07-02 204427](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/d7044f5c-ba9a-4a19-9875-6dc3ffe01e8a)

![Screenshot 2024-07-02 204549](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/a6bdd280-e5db-4fc5-b9b4-ccbf536b8a56)

![Screenshot 2024-07-02 204636](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/174557553/31c8deec-b713-4959-bfc7-1ffdc4d2777f)

**Comment by BlackHole338** [comment]
Top image is what the armor usually looks like when worn. Dark black dragons are the amethyst lightning dragons without textures.

**Comment by IAFEnvoy** [comment]
Some of these issues have been fixed in previous issues. You can also take a look

**Comment by IAFEnvoy** [comment]
You can get the latest alpha build in Github Action Page

**Comment by IAFEnvoy** [comment]
I have sorted your bug lists, and I need more information for some of them.

`Fixed in #xx`: This bug has been fixed in previous issue(s). You can confirm the fix by downloading latest version on CurseForge or GitHub Action.

`Fixed in Push`: Same to above but I found this bug by myself.

`Need More Info`: I need more information to find out the problem.

`Confirmed bug`: Successfully reproduced on my computer or an existed issue and wait to fix.

Crashes:

1. - [X] **(Fixed in #13)** Shift click equipping dragon armor in the dragon stats interface crashes the game

2. - [ ] **(Need More Info)** Equipping troll armor crashes the game

3. - [ ] **(Confirmed bug)** Placing a dreadstone torch crashes the game


Bugs:
1. -Cyclops turns invisible for a few seconds occasionally

2. - [X] **(Fixed in #11)** Ice and fire armor is not correctly shown on the player when equipped except for myrmex armor,(works) sheep disguise armor,(works) and dragon scale armor.(Has no texture)

3. - [X] **(Fixed in #5)** Most particle effects do not have a texture including hydra spit, siren heart particles, dread torches, dread lich magic, and pixie dust.

4. - [X] **(Fixed in Push)** Dragons can't be stored in the dragon horn, it just deletes them and makes the horn unusable

5. - [X] **(Fixed in Push)** Equipment that applies effects will apply it without being equipped. The blindfold applies blindness while being in the inventory instead of while being equipped and the tide guardian armor applies water breathing while just being in the inventory.

6. -When you use the cockatrice scepter on an enemy the wither beam keeps going in the direction you shot it until you right click even when the enemy is dead. This is visible if you go in 3rd person or look at yourself in your inventory.

7. - [ ] **(Confirmed bug)** All arrows except dragon bone arrows cannot be used

8. - [ ] **(Confirmed bug)** Chain lines function correctly but visibly they never disappear until the mob is killed and the chain goes in a random direction instead of towards the block.

9. - [X] **(Fixed in #18 maybe?)** Death worm gauntlet when used does not latch out towards enemies but instead extends in the inventory and model visually.

10. - [ ] **(Need More Info)** Regular fire dragon breath does not create fire effects.

11. - [ ] **(Confirmed bug #17)** Siren flute effect does not work

12. - [ ] **(Confirmed bug)** Lightning dragons will keep blasting lightning in the same spot instead of redirecting it to where their enemy moved

13. - [X] **(Fixed in #7)** Amethyst lighting dragon scales and amethyst lightning dragons do not have textures but still function

14. - [ ] **(Confirmed bug #17)** Sirens can't lure you in

15. - [X] **(Fixed in #6)**  Troll weapons are invisible

16. - [ ] **(Need More Info)** Myrmex queen disappears permanently through the wall or suffocates in the wall. This happens every time a myrmex queen is generated.
